### PR TITLE
stateManagement currentQuery calls getPaginator incorrectly #29

### PR DESCRIPTION
**Pull request by jlaramie**

### CODE REVIEW

**Comment by sslotsky** [comment]
Good catch, thanks for the PR! So, a couple of thoughts. 

1. I'm planning to merge the V3 branch into master (this has been a long time coming). If the issue still exists in V3, at that point you could rebase and I'd be glad to merge.
2. I've actually moved this project to [@orange-marmalade/paginate-this](https://www.npmjs.com/package/@orange-marmalade/paginate-this). I'm planning to deprecate this package in favor of that one, but I haven't gotten around to doing it. Do you mind submitting this change to that project as well?

**Comment by sslotsky** [comment]
You know what @jlaramie on second thought, keep this one open. I don't want to force you to upgrade to V3 in order to have your change, because V3 has some breaking changes.

**Comment by jlaramie** [comment]
The exact same fix is applicable to V3. Exactly the same fix I can produce a pull request for that.

**Comment by jlaramie** [comment]
@sslotsky why the change of repo? I personally had some issues with V3 which is why I moved to V2 but now that I've gotten used to it I might try V3 or this new repo again.

**Comment by sslotsky** [comment]
@jlaramie good question. Honestly, the only reason for the move was to change the name. `violet` is a css framework that one of my coworkers built, and this was originally meant to be a simple pagination library that used those styles. As time went on, it made sense to go through a bit of a divorce, as `violet` has very little to do with what this library does.

Unfortunately, `npm` doesn't really allow you to simply rename packages, so creating a new repo and deprecating is the only option :(

**Comment by sslotsky** [comment]
This is now available @2.0.6

**Pull request merged**
